package com.digital.common.enums;

public enum CustomErrorCode {
    INTERNAL_SERVER_ERROR,
    VALIDATION_ERROR,
    RESOURCE_NOT_FOUND,
    MALFORMED_JSON,
    ACCESS_DENIED,
    SHOPPER_LOCATION_NOT_EXIST,
    SHOPPER_LOCATION_MENU_ITEM_NOT_EXIST,
    SHOPPER_FEIGN_CLIENT_ERROR,
    CONSUMER_ORDER_NOT_FOUND,
    CONSUMER_NOT_FOUND,
    SHOPPER_NOT_FOUND,
    LOCATION_NOT_FOUND
}
